### ISSUE TITLE
Invalid scope for client

### ISSUE THREAD

**Issue by andrui** [XeroAPI/xero-node-bankfeeds#2]
Hi,

When "scope" contains "bankfeeds", then during xero connection when you are redirected to the https://login.xero.com/identity/connect/authorize... Xero respond with error.

![image](https://user-images.githubusercontent.com/10127795/80350631-b35f2980-8879-11ea-8020-f066937e51f4.png)

Did you have any successes "bankfeeds" API usage?

**Comment by andrui** [comment]
May it be caused by the fact that my test app is not certified?

**Comment by SidneyAllen** [comment]
@andrui - we restrict access to this API to our bank partners.

If you work for a bank should email api@xero.com and request access to the bank feeds API so we can enable the proper scopes your Xero OAuth 2 app.
